// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasswordManager_API.Context;

#nullable disable

namespace PasswordManager_API.Migrations
{
    [DbContext(typeof(PasswordManagerDbContext))]
    [Migration("20250515184043_Implement")]
    partial class Implement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PasswordManager_API.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordNonce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserNameNonce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNameTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsernameTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("PasswordManager_API.Entities.LookupItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LookupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LookupItems");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3242),
                            IsActive = true,
                            LookupTypeId = 1,
                            Name = "Jordanian"
                        },
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3243),
                            IsActive = true,
                            LookupTypeId = 2,
                            Name = "Client"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3244),
                            IsActive = true,
                            LookupTypeId = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3245),
                            IsActive = true,
                            LookupTypeId = 2,
                            Name = "Driver"
                        },
                        new
                        {
                            Id = 100,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3246),
                            IsActive = true,
                            LookupTypeId = 3,
                            Name = "Phone"
                        },
                        new
                        {
                            Id = 101,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3246),
                            IsActive = true,
                            LookupTypeId = 3,
                            Name = "Name"
                        },
                        new
                        {
                            Id = 102,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3247),
                            IsActive = true,
                            LookupTypeId = 3,
                            Name = "Email"
                        },
                        new
                        {
                            Id = 103,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3248),
                            IsActive = true,
                            LookupTypeId = 3,
                            Name = "UserName"
                        },
                        new
                        {
                            Id = 104,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3249),
                            IsActive = true,
                            LookupTypeId = 3,
                            Name = "National ID"
                        },
                        new
                        {
                            Id = 200,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3249),
                            IsActive = true,
                            LookupTypeId = 4,
                            Name = "Trainer"
                        },
                        new
                        {
                            Id = 201,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3250),
                            IsActive = true,
                            LookupTypeId = 4,
                            Name = "Trainere"
                        },
                        new
                        {
                            Id = 300,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3251),
                            IsActive = true,
                            LookupTypeId = 5,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = 301,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3252),
                            IsActive = true,
                            LookupTypeId = 5,
                            Name = "Banking"
                        },
                        new
                        {
                            Id = 302,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3252),
                            IsActive = true,
                            LookupTypeId = 5,
                            Name = "Social Media"
                        },
                        new
                        {
                            Id = 303,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3253),
                            IsActive = true,
                            LookupTypeId = 5,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("PasswordManager_API.Entities.LookupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LookupTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3138),
                            IsActive = true,
                            Name = "Nationality"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3153),
                            IsActive = true,
                            Name = "Role"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3154),
                            IsActive = true,
                            Name = "UsernameType"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3155),
                            IsActive = true,
                            Name = "Specialization"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3156),
                            IsActive = true,
                            Name = "Category"
                        });
                });

            modelBuilder.Entity("PasswordManager_API.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("PasswordManager_API.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("PasswordManager_API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLoggedIn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerfied")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OTPCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OTPExipry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreationDate = new DateTime(2025, 5, 15, 21, 40, 43, 433, DateTimeKind.Local).AddTicks(3273),
                            Email = "b846bad23206df937f768e06362affb42a22ea8658c2403642b2a0049e81709297ad89e2a7946c48be8462dcd622f169",
                            IsActive = true,
                            IsVerfied = true,
                            Password = "d62915f355cf243d2d90f2d7c506af00baee5d3e8d3870d656a354fcd0a25c87c9b648a6f2c59ece1bfb002d5d2c0567",
                            RoleId = 2,
                            UserName = "fc8c0c79545bb5e9afe969574c81eeabe7702cad289584b0b19dfedfbeb338a626b855a7ddb54a9ff0a9b73c76cb3fdf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
